// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lsEnum.proto

#include "lsEnum.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace lspb {
}  // namespace lspb
static constexpr ::PROTOBUF_NAMESPACE_ID::Metadata* file_level_metadata_lsEnum_2eproto = nullptr;
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_lsEnum_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_lsEnum_2eproto = nullptr;
const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_lsEnum_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_lsEnum_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\014lsEnum.proto\022\004lspb*&\n\010ModuleId\022\020\n\014Unkn"
  "ownModel\020\000\022\010\n\004Game\020\001*>\n\006Result\022\013\n\007succes"
  "s\020\000\022\007\n\003err\020\001\022\017\n\013errNoMethod\020\002\022\r\n\terrNulM"
  "sg\020\003B\022\n\020org.bro.lssrv.pbb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_lsEnum_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_lsEnum_2eproto_sccs[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_lsEnum_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_lsEnum_2eproto = {
  false, false, descriptor_table_protodef_lsEnum_2eproto, "lsEnum.proto", 152,
  &descriptor_table_lsEnum_2eproto_once, descriptor_table_lsEnum_2eproto_sccs, descriptor_table_lsEnum_2eproto_deps, 0, 0,
  schemas, file_default_instances, TableStruct_lsEnum_2eproto::offsets,
  file_level_metadata_lsEnum_2eproto, 0, file_level_enum_descriptors_lsEnum_2eproto, file_level_service_descriptors_lsEnum_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_lsEnum_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_lsEnum_2eproto)), true);
namespace lspb {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ModuleId_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_lsEnum_2eproto);
  return file_level_enum_descriptors_lsEnum_2eproto[0];
}
bool ModuleId_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Result_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_lsEnum_2eproto);
  return file_level_enum_descriptors_lsEnum_2eproto[1];
}
bool Result_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace lspb
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
